#!/usr/bin/env python3
"""Create cave-category JSONL files from the 19 seed-dataset volumes.

The output schema intentionally matches ``cave6/split_cave6_categorized.jsonl``:
entry_id, name, images (path only), description, and category.

This is a provisional, deterministic categorization pass. The sixth-cave file
was manually reviewed and is therefore copied into the manifest as the
reference rather than regenerated by these heuristics.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path


CATEGORIES = ("佛教故事", "人物造像", "建筑空间", "装饰纹样")

# Volume labels are the finest cave boundary available in the seed dataset.
# Volumes covering several caves are kept together instead of guessing a page
# boundary from prose that may mention neighboring caves. The full sixth-cave
# file is generated from volumes 03 and 04; the existing 331-row file remains
# the manually reviewed reference subset.
VOLUME_GROUPS = {
    "caves_01-04": (1,),
    "cave_05": (2,),
    "cave_06_full": (3, 4),
    "cave_07": (5,),
    "cave_08": (6,),
    "cave_09": (7,),
    "cave_10": (8,),
    "cave_11": (9,),
    "cave_12": (10,),
    "cave_13": (11,),
    "caves_14-15-16-1": (12,),
    "cave_16": (13,),
    "cave_17": (14,),
    "cave_18": (15,),
    "cave_19": (16,),
    "cave_20_and_excavated": (17,),
    "caves_21-31": (18,),
    "caves_32-45": (19,),
}

# Narrative terms are deliberately narrow. Words such as “佛” and “菩萨”
# occur in ordinary figure descriptions and must not turn those into stories.
STORY_TERMS = (
    "本生",
    "佛传",
    "佛教故事",
    "故事画",
    "因缘",
    "维摩诘",
    "涅槃",
    "降魔",
    "燃灯",
    "鹿王",
    "萨埵",
    "舍身",
)
FIGURE_TERMS = (
    "天王",
    "金刚神",
    "飞天",
    "菩萨",
    "佛像",
    "坐佛",
    "立佛",
    "弟子",
    "供养",
    "伎乐",
    "乐伎",
    "梵志",
    "比丘",
    "童子",
    "人物",
    "主尊",
    "龙首",
)
ARCHITECTURE_TERMS = (
    "外景",
    "窟门",
    "窟顶",
    "窟檐",
    "前室",
    "后室",
    "甬道",
    "明窗",
    "建筑",
    "楼阁",
    "院落",
    "崖面",
    "洞窟形制",
    "中心塔柱",
    "塔柱",
    "壁面",
    "全窟",
    "窟内",
)
DECORATION_TERMS = (
    "纹饰",
    "纹样",
    "忍冬纹",
    "莲花纹",
    "莲瓣纹",
    "装饰图案",
    "装饰纹",
    "藻井",
    "瓦当",
    "图案",
    "雕饰",
    "宝缯",
    "背光",
)


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def category(name: str, description: str) -> str:
    text = f"{name} {description}"
    if any(term in text for term in STORY_TERMS):
        return "佛教故事"

    # A named figure/detail is more specific than the surrounding wall or
    # chamber description. This ordering mirrors the sixth-cave annotations.
    if any(term in name for term in FIGURE_TERMS):
        return "人物造像"
    if any(term in name for term in DECORATION_TERMS):
        return "装饰纹样"
    if any(term in name for term in ARCHITECTURE_TERMS):
        return "建筑空间"
    if any(term in text for term in DECORATION_TERMS):
        return "装饰纹样"
    if any(term in text for term in FIGURE_TERMS):
        return "人物造像"
    if any(term in text for term in ARCHITECTURE_TERMS):
        return "建筑空间"
    return "人物造像"


def output_record(entry: dict) -> dict:
    images = []
    for image in entry.get("images", []):
        path = image.get("path", "")
        if path.startswith("seed_dataset/"):
            normalized = path
        else:
            normalized = f"seed_dataset/{path.lstrip('/')}"
        images.append({"path": normalized})
    return {
        "entry_id": entry["entry_id"],
        "name": entry.get("name", ""),
        "images": images,
        "description": entry.get("description", ""),
        "category": category(entry.get("name", ""), entry.get("description", "")),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed-dir", default="seed_dataset")
    parser.add_argument("--output-dir", default="cave6/cave_category_splits")
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parents[1]
    seed_dir = (project_root / args.seed_dir).resolve()
    output_dir = (project_root / args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest = {
        "schema": ["entry_id", "name", "images", "description", "category"],
        "categories": list(CATEGORIES),
        "classification": "deterministic provisional keyword pass; review before publication",
        "reference": "cave6/split_cave6_categorized.jsonl",
        "files": {},
    }
    total = 0
    for group_name, volumes in VOLUME_GROUPS.items():
        source_paths = [seed_dir / f"volume_{volume:02d}.json" for volume in volumes]
        entries = []
        for source in source_paths:
            entries.extend(read_json(source).get("entries", []))
        records = [output_record(entry) for entry in entries]
        records.sort(key=lambda item: item["entry_id"])
        for record in records:
            if not record["images"]:
                raise SystemExit(f"Entry has no image: {record['entry_id']}")
            for image in record["images"]:
                if not (project_root / image["path"]).is_file():
                    raise SystemExit(f"Missing image for {record['entry_id']}: {image['path']}")
        output = output_dir / f"split_{group_name}_categorized.jsonl"
        with output.open("w", encoding="utf-8") as handle:
            for record in records:
                handle.write(json.dumps(record, ensure_ascii=False, separators=(",", ":")) + "\n")
        counts = Counter(record["category"] for record in records)
        manifest["files"][group_name] = {
            "source": [str(path.relative_to(project_root)) for path in source_paths],
            "output": str(output.relative_to(project_root)),
            "count": len(records),
            "category_counts": dict(sorted(counts.items())),
        }
        total += len(records)

    manifest["total_records"] = total
    manifest_path = output_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"total_records": total, "files": len(VOLUME_GROUPS)}, ensure_ascii=False))
    for group_name, info in manifest["files"].items():
        print(group_name, info["count"], info["category_counts"])


if __name__ == "__main__":
    main()
